### ISSUE TITLE
Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by Arthurvdv** [SimonOfHH/D365BCAppHelper#20]
I'm note sure if the D365BCAppHelper is supported with a Azure DevOps pipeline on Linux or that I've encountered an bug.

After the install and import of the PowerShell module I hit an error on the `Get-D365BCManifestFromAppFile` function; ```Cannot bind argument to parameter 'Path' because it is null.```

```YAML
pool:
  vmImage: ubuntu-latest

- task: PowerShell@2
  displayName: 'Retrieve info from App'
  env:
    FILE: $(BcArtifactFile)
  inputs:
    targetType: 'inline'
    script: |
      Install-Module D365BCAppHelper -Force
      Import-Module D365BCAppHelper -DisableNameChecking
      Get-D365BCManifestFromAppFile -Filename "$env:FILE"
```

```
Starting: Retrieve info from App
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.232.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/home/vsts/work/_temp/89ac2bfa-44ff-4a62-a80e-39a9f92f85fe.ps1'
Copy-FileToTemporaryLocation: /home/vsts/.local/share/powershell/Modules/D365BCAppHelper/0.0.0.27/Export/Private/Get-D365BCManifestFromAppFile.ps1:243
Line |
 243 |  …          $Filename = Copy-FileToTemporaryLocation -Filename $Filename
     |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

##[error]PowerShell exited with code '1'.
Finishing: Retrieve info from App
```
